name: Ticket
description: Create a new Flask ticket
title: "[TICKET] "
labels: ["status:create"]
body:
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - Bug
        - Feature
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      options:
        - priority:low
        - priority:medium
        - priority:high
        - priority:critical
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
